%% Read spike times from the npy files generated by spyking circus
clear;clc;close all; tic;
path = 'Z:\TDTData\Acute_Neuromod_New-200929-144807\';
savepath = 'C:\Users\AbbasiM\Documents\MATLAB\AcuteCb_AA\Data\';
blocks = {'I070-201006_DAT_files','I071-201008_DAT_files','I072-201009_DAT_files'}; 
folder = '\SU_CONT\SU_CONT.GUI\';
totChans = 32;
spkwflen_before = 15; % in samples
spkwflen_after  = 16;
fs = 2.441406250000000e+04;
for i=3%1:length(blocks)
  for ch = 1:totChans
    spike_times    = double(readNPY([path,blocks{i},'\Channel_',num2str(ch),folder,'spike_times.npy']));
    spike_clusters = readNPY([path,blocks{i},'\Channel_',num2str(ch),folder,'spike_clusters.npy']);
    f = tdfread([path,blocks{i},'\Channel_',num2str(ch),folder,'cluster_group.tsv']); 
    cluster_labels = deblank(string(f.group));
    cluster_id     = f.cluster_id;
    valid_clusters = cluster_id(strcmp(cluster_labels,"mua")|strcmp(cluster_labels,"good"));
    curChanPath = [path,blocks{i},'\Channel_',num2str(ch),'\SU_CONT.dat'];
    fiD = fopen(curChanPath,'r');
    curChan_cont = fread(fiD,'float32');
    for unit=min(valid_clusters):max(valid_clusters)
      st = (spike_times(spike_clusters==unit))';
      if ~isempty(st)
        for w=1:10
          disp(['ch ',num2str(ch),' u ',num2str(unit), ' st ', num2str(w)]);
          samples = ((st(w))-spkwflen_before):((st(w))+spkwflen_after);
          valid_inds = logical(((1:length(curChan_cont))>samples(1)).*((1:length(curChan_cont))<samples(end)));
          wf(:,w) = curChan_cont(valid_inds);
        end
        TimeStamps{ch,unit+1} = st./fs;
        Waves{ch,unit+1} = wf;
      end
      clear wf
    end
  end
  if ~exist([savepath,blocks{i}(1:4)], 'dir')
    mkdir([savepath,blocks{i}(1:4)]);
  end
  save([savepath,blocks{i}(1:4),'\data.mat'], 'TimeStamps','Waves','-append');
end
runTime = toc;
disp(['done! time elapsed (hours) - ', num2str(runTime/3600)]);